# Generated by Django 4.2.11 on 2024-03-27 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_listcars_motor_rename_imgcar_motor_imgmotor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('borrow_count', models.IntegerField(default=0)),
                ('published_date', models.DateField(default=datetime.date.today)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
