# Generated by Django 4.2.11 on 2024-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
